PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>
PREFIX ex: <http://ex.org/ns/ex#>
select *  WHERE {
	?s1 schema:givenName ?name;
	    schema:familyName ?familyName;
	    schema:email ?email;
	    ex:hasCountry ?country.
  	?country ex:officialName ?officialName.
}
