#!/bin/bash
arg1=$1
arg2=$4
delimiter=$3
col=$2
file=$5
echo ARG1:$arg1 ARG2:$arg2 DELIM:$delimiter COL:$col FILE:$file
awk -F '\",\"' '{print $col}' tmp/$file | awk  -F '' '{print $1$2$3$4"-"$5$6"-"$7$8}' > tmp/$file.tmp
awk -F, '{getline f1 <"tmp/$file.tmp" ;print $arg2}' OFS=, tmp/$file > salida.csv

