#!/bin/bash
arg1=$1
col="$"$2
delimiter=$3
arg2=$4
file=$5

echo ARG1:$arg1 ARG2:$arg2 DELIM:$delimiter COL:$col FILE:$file
#awk -F '\",\"' '{print $col}' tmp/$file | awk  -F '' '{print $1$2$3$4"-"$5$6"-"$7$8}' > tmp/$file.tmp
#awk -F, '{getline f1 <"tmp/$file.tmp" ;print $arg2}' OFS=, tmp/$file > salida.csv

echo $col
awk -F '\",\"' "{print $col }" tmp/$file | awk  -F '' '{print $1$2$3$4"-"$5$6"-"$7$8}' >tmp/$file.tmp
awk -F '\",\"'  "{getline f1 <\"tmp/$file.tmp\" ;print $arg2}" OFS='\",\"' tmp/$file  > salida_tmp.csv
mv  salida_tmp.csv tmp/$file
#ARG1:$3"-"$2"-"$1 ARG2:$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, f1, $16, DELIM:none COL:$15 FILE:gene_info