#!/bin/bash
arg1=$1
col="$"$2
delimiter=$3
arg2=$4
file=$5

#echo ARG1:$arg1 ARG2:$arg2 DELIM:$delimiter COL:$col FILE:$file
awk -F '\",\"' "{print $col }" tmp/$file | awk  -F$delimiter "{print $arg1}" >tmp/$file.tmp
awk -F '\",\"'  "{getline f1 <\"tmp/$file.tmp\" ;print $arg2}" OFS='\",\"' tmp/$file  > salida_tmp.csv
mv  salida_tmp.csv tmp/$file
