#!/bin/bash
delimiter=$1
all='$0'
arg=$2
cols=$3
split=$4
file=$5
newDelimiter="'\",\"'"
#echo DELIMITER:$delimiter ARG1:$arg ARG2:$cols ARG3:$split
{ rm tmp/csv/$file && awk -F "$delimiter" " FNR>1 {$split{$arg print $cols}}" | tr -d "\r"|sort -u > tmp/csv/$file;} < tmp/csv/$file
echo  awk -F "$delimiter" "{$split{$arg print $cols}}" tmp/$file
