#!/bin/bash
delimiter=$1
all='$0'
arg=$2
cols=$3
split=$4
file=$5
newDelimiter="'\",\"'"
#echo DELIMITER:$delimiter ARG1:$arg ARG2:$cols
{ rm tmp/$file && awk -F "$delimiter" "{$split{$arg print $cols}}" > tmp/$file;} < tmp/$file
#echo  awk -F "$delimiter" "{$split{$arg print $cols}}" tmp/$file
